-- 0) Helpful extensions/types
CREATE EXTENSION IF NOT EXISTS citext;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'season_enum') THEN
    CREATE TYPE season_enum AS ENUM ('spring', 'summer', 'fall');
  END IF;
END$$;

-- 1) Core tables

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_telegram_id BIGINT UNIQUE,
  CHECK (user_telegram_id IS NULL OR user_telegram_id > 0)
);

CREATE TABLE IF NOT EXISTS department (
  dept_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS instructor (
  instructor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_id       BIGINT NOT NULL REFERENCES department(dept_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
  email         CITEXT NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_instructor_dept_id ON instructor(dept_id);

CREATE TABLE IF NOT EXISTS course (
  course_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS semester (
  semester_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "year"      INT NOT NULL,
  season      season_enum NOT NULL,
  CONSTRAINT ck_semester_year_range
    CHECK ("year" BETWEEN 1390 AND (EXTRACT(YEAR FROM now())::int)),
  CONSTRAINT uq_semester_year_season UNIQUE ("year", season)
);

CREATE TABLE IF NOT EXISTS available_course (
  ac_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instructor_id BIGINT NOT NULL REFERENCES instructor(instructor_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
  semester_id   BIGINT NOT NULL REFERENCES semester(semester_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
  course_id     BIGINT NOT NULL REFERENCES course(course_id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT uq_available_course UNIQUE (instructor_id, semester_id, course_id)
);
CREATE INDEX IF NOT EXISTS idx_ac_instructor_id ON available_course(instructor_id);
CREATE INDEX IF NOT EXISTS idx_ac_semester_id   ON available_course(semester_id);
CREATE INDEX IF NOT EXISTS idx_ac_course_id     ON available_course(course_id);

-- 2) Upsert-style timestamp trigger (for updated_at)

CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3) Assessments

CREATE TABLE IF NOT EXISTS instructor_assessment (
  assessment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id             BIGINT NOT NULL REFERENCES users(user_id)
                       ON UPDATE CASCADE ON DELETE RESTRICT,
  available_course_id BIGINT NOT NULL REFERENCES available_course(ac_id)
                       ON UPDATE CASCADE ON DELETE CASCADE,

  -- ratings 1..5 unless noted; all nullable by your spec
  instructor_presence_importance     SMALLINT CHECK (instructor_presence_importance BETWEEN 1 AND 5),
  instructor_course_scoring          SMALLINT CHECK (instructor_course_scoring      BETWEEN 1 AND 5),
  instructor_resource_completeness   SMALLINT CHECK (instructor_resource_completeness BETWEEN 1 AND 5),
  instructor_knowledge               SMALLINT CHECK (instructor_knowledge           BETWEEN 1 AND 5),
  instructor_teaching_skill          SMALLINT CHECK (instructor_teaching_skill      BETWEEN 1 AND 5),
  instructor_class_time_management   SMALLINT CHECK (instructor_class_time_management BETWEEN 1 AND 5),
  instructor_answering               SMALLINT CHECK (instructor_answering           BETWEEN 1 AND 5),
  instructor_politeness              SMALLINT CHECK (instructor_politeness          BETWEEN 1 AND 5),

  instructor_overall                 SMALLINT CHECK (instructor_overall BETWEEN 1 AND 10),

  course_content_worth               SMALLINT CHECK (course_content_worth           BETWEEN 1 AND 5),

  student_final_score                NUMERIC(4,2),
  CONSTRAINT ck_student_final_score_range
    CHECK (student_final_score IS NULL
           OR (student_final_score >= 0.00 AND student_final_score <= 20.00)),

  student_class_presence             SMALLINT CHECK (student_class_presence BETWEEN 0 AND 100),

  student_assessment                 TEXT,
  student_allow_show_id              BOOLEAN NOT NULL DEFAULT FALSE,

  created_at                         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                         TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT uq_assessment_once_per_course UNIQUE (user_id, available_course_id)
);
CREATE INDEX IF NOT EXISTS idx_assessment_user_id ON instructor_assessment(user_id);
CREATE INDEX IF NOT EXISTS idx_assessment_ac_id   ON instructor_assessment(available_course_id);

-- attach the trigger (safe to re-create)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'set_timestamp_on_instructor_assessment'
  ) THEN
    CREATE TRIGGER set_timestamp_on_instructor_assessment
    BEFORE UPDATE ON instructor_assessment
    FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();
  END IF;
END$$;